MODEL:
  LABEL: [
  "aeroplane",
  "bicycle",
  "bird",
  "boat",
  "bottle",
  "bus",
  "car",
  "cat",
  "chair",
  "cow",
  "diningtable",
  "dog",
  "horse",
  "motorbike",
  "person",
  "pottedplant",
  "sheep",
  "sofa",
  "train",
  "tvmonitor"
  ]
  numcls: 20
  gt_per_grid: 3
  modeltype: StrongerV1
  backbone: 'darknet53'
  backbone_pretrained: 'checkpoints/darknet.pth'
EVAL:
  varvote: True
  soft: False
EXPER:
  experiment_name: 'strongerv2'
DATASET:
  dataset: 'VOC'

OPTIM:
  batch_size: 8
  lr_initial: 2e-4
  total_epoch: 60
  milestones: [30,45]

Prune:
  sparse: False

devices: (1,)