MODEL:
  LABEL: [
  "aeroplane",
  "bicycle",
  "bird",
  "boat",
  "bottle",
  "bus",
  "car",
  "cat",
  "chair",
  "cow",
  "diningtable",
  "dog",
  "horse",
  "motorbike",
  "person",
  "pottedplant",
  "sheep",
  "sofa",
  "train",
  "tvmonitor"
  ]
  numcls: 20
  modeltype: StrongerV3_US
  backbone: 'USMobileNetV2'
  backbone_pretrained: 'checkpoints/mobilenet_v2.pth'
EXPER:
  experiment_name: 'strongerv3US'
  resume: 'best'
  US_training: True
DATASET:
  dataset: 'VOC'

OPTIM:
  batch_size: 12
  lr_initial: 2e-4
  total_epoch: 60
  milestones: [30,45]

Prune:
  sparse: False